name: technotheque_vr_website
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  common:

dependency_overrides:
  common:
    path: ../common
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts: 
    - family: Lato
      fonts:
        - asset: ../common/fonts/Lato/Lato-Regular.ttf
        - asset: ../common/fonts/Lato/Lato-Italic.ttf
          style: italic
        - asset: ../common/fonts/Lato/Lato-Bold.ttf
          weight: 700